config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  get 'sessions/new'
  get 'users/new'
  get 'welcome/index'
  get 'appstore/likes'
  get 'appstore/dislikes'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    get :likes
    get :dislikes
  end

  resources :licenceplates do
    put :downvote
    put :upvote
    get :likes
    get :dislikes
  end
  resources :appstore do
    put :downvote
    put :upvote
    # get :likes
    # get :dislikes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_voter
  acts_as_votable
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update destroy likes dislikes]
  before_action :admin_user,     only: %i[destroy index]

  def index
    @users = User.all
  end

  def show
    @user = if current_user.admin?
              User.find(params[:id])
            else
              User.find(current_user[:id])
            end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Plate Rank homie!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def likes
    if !current_user.nil? && current_user.admin?
      @user = User.find(params[:user_id])
      @likes = User.find(params[:user_id]).find_up_voted_items
    else
      @user = User.find(current_user[:id])
      @likes = current_user.find_up_voted_items
    end
  end

  def dislikes
    if !current_user.nil? && current_user.admin?
      @user = User.find(params[:user_id])
      @dislikes = User.find(params[:user_id]).find_down_voted_items
    else
      @user = User.find(current_user[:id])
      @dislikes = current_user.find_down_voted_items
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = "Please log in."
    redirect_to login_url
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/dislikes.html.erb
<% content_for :title, @user.name %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<!-- Row -->
<div class="row mb-0">
  <div class="col m8 offset-m2 s12">
    <h4 class="hide-on-small-only">👎 Thumbs Down <%= @user.find_disliked_items.size %></h4>
    <h4 class="center-align hide-on-med-and-up">👎 Thumbs Down <%= @user.find_disliked_items.size %></h4>
  </div>
  <!-- Table -->
  <table class="striped centered col m8 offset-m2 s12">
    <!-- Table Headers -->
    <thead>
      <tr>
        <th><h5>🚘</h5></th>
        <th><h5>📆</h5></th>
      </tr>
    </thead>
    <!-- ./Table Headers -->
    <!-- Table Body -->
    <tbody>
    <% @dislikes.each do |dislike| %>
      <% if !dislike[:plate].nil? %>
        <tr>
          <td><%= link_to dislike[:plate].upcase, licenceplate_path(dislike[:id]) %></td>
          <td><%= dislike[:created_at].strftime("%Y-%m-%d") %></td>
        </tr>
      <% end %>
    <%end %>
    </tbody>
    <!-- ./Table Body -->
  </table>
  <!-- ./Table -->
</div>
<!-- ./Row -->

<!-- Nav Links -->
<div class="row center-align">
  <div class="col m6 offset-m3 s10 offset-s1">
    <%= link_to raw("👈"), current_user, class: "waves-effect waves-light btn-large green mt-3", style: "width:100%" %>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :title, @user.name %>
<div class="row">
  <div class="col m8 offset-m2">
    <h3 class="hide-on-small-only">Update Your Profile</h3>
    <h5 class="hide-on-med-and-up">Update Profile</h5>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control mb-xs-3' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control mb-xs-3' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control mb-xs-3' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control mb-xs-3' %>

      <%= f.submit "👌 Save changes", class: "waves-effect waves-light btn-large green mt-3" %>
      <span>&nbsp;&nbsp;</span>
      <%= link_to "👈 Cancel", current_user, class: "waves-effect waves-light btn-large red mt-3" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '🔑 Admin') %>
<h4><strong class="orange-text">🔑ADMIN:</strong> All Users</h4>
<div class="row mb-1 center-align">
  <div class="col s4">
    <h5>🕵️‍♂️</h5>
  </div>
  <div class="col s2">
    <h5>🏁</h5>
  </div>
  <div class="col s2">
    <h5>👍</h5>
  </div>
  <div class="col s2">
    <h5>👎</h5>
  </div>
  <div class="col s2">
    <h5>🛑</h5>
  </div>
</div>
<div class="row center-align">
  <% @users.each do |user| %>

    <!-- User -->
    <div class="col s4">
      <%= link_to user.name, user%>
    </div>

    <!-- Total Votes -->
    <div class="col s2">
      <%= user.find_voted_items.size%>
    </div>

    <!-- Upvotes -->
    <div class="col s2">
      <%= user.find_liked_items.size%>
    </div>

    <!-- Downvotes -->
    <div class="col s2">
      <%= user.find_disliked_items.size%>
    </div>

    <!-- Delete -->
    <div class="col s2">
      <% if !current_user.nil? && current_user.admin? && !current_user?(user) %>
        <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" }, class: "red-text" %>
      <% else %>
        <span>admin</span>
      <% end%>
    </div>

  <% end %>
</div>

app/views/users/likes.html.erb
<% content_for :title, @user.name %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<!-- Row -->
<div class="row mb-0">
  <div class="col m8 offset-m2 s12">
    <h3>Likes</h3>
  </div>
  <!-- Table -->
  <table class="striped centered col m8 offset-m2 s12">
    <!-- Table Headers -->
    <thead>
      <tr>
        <th><h4>🚘</h4></th>
        <th><h4>📆</h4></th>
      </tr>
    </thead>
    <!-- ./Table Headers -->
    <!-- Table Body -->
    <tbody>
    <% @likes.each do |like| %>
      <% if !like[:plate].nil? %>
        <tr>
          <td><%= link_to like[:plate], licenceplate_path(like[:id]) %></td>
          <td><%= link_to like[:created_at].strftime("%d-%m-%Y"), licenceplate_path(like[:id]) %></td>
        </tr>
      <% end %>
    <%end %>
    </tbody>
    <!-- ./Table Body -->
  </table>
  <!-- ./Table -->
</div>
<!-- ./Row -->

<!-- Nav Links - Mobile Only -->
<div class="row hide-on-med-and-up center-align">
  <div class="col m8 offset-m2 s4">
    <%= link_to raw("👈"), current_user, class: "waves-effect waves-light btn-large green mt-3", style: "width:100%" %>
  </div>
  <div class="col s4">
    <%= link_to raw("🏁"), licenceplates_path, class: "waves-effect waves-light btn-large orange mt-3", style: "width:100%", :method => :get %>
  </div>
  <div class="col s4">
    <%= link_to raw("🏡"), welcome_index_path, class: "waves-effect waves-light btn-large blue mt-3", style: "width:100%", :method => :get %>
  </div>
</div>
<!-- Nav Links - Desktop Only -->
<div class="row hide-on-small-only">
  <div class="col m2 offset-m2 s3">
    <%= link_to raw("👈&nbsp;Back"), current_user, class: "waves-effect waves-light btn-large green mt-3", style: "width:100%" %>
  </div>
  <div class="col m2 s3">
    <%= link_to raw("🏁&nbsp;View Rankings"), licenceplates_path, class: "waves-effect waves-light btn-large orange mt-3",style: "width:100%", :method => :get %>
  </div>
  <div class="col m2  s3">
    <%= link_to raw("🏡&nbsp;Home"), welcome_index_path, class: "waves-effect waves-light btn-large blue mt-3",style: "width:100%", :method => :get %>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :title, "Sign Up ✏️" %>
<div class="row">
  <div class="col m8 offset-m2">
    <h3 class="hide-on-small-only">✏️ Sign Up</h3>
    <h5 class="hide-on-med-and-up">✏️ Sign Up</h5>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "User Name" %>
      <%= f.text_field :name, class: 'form-control mb-xs-3' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control mb-xs-3' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control mb-xs-3' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control mb-xs-3' %>

      <%= f.submit "Create my account 🤘", class: "waves-effect waves-light btn-large green mt-3" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title, @user.name %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<h3><%= @user.name %></h3>
<p><strong>Email </strong> <%= @user.email %></p>
<p><strong>Joined </strong></strong><%= @user.created_at.strftime("%B %d, %Y") %></p>
<p><strong><%= @user.find_voted_items.size %></strong> Total Votes</p>
<p><strong><%= @user.find_liked_items.size %></strong> <a href="/users/<%= @user.id %>/likes">Thumbs Up</a></p>
<p><strong><%= @user.find_disliked_items.size %></strong> <a href="/users/<%= @user.id %>/dislikes">Thumbs Down</a></p>

<!-- Nav Links - Mobile Only -->
<div class="row mb-0">
  <div class="col s6 m3">
    <%= link_to raw("✏️&nbsp;&nbsp;Edit"), edit_user_path(current_user), class: "waves-effect waves-light btn-large green mt-3", style: "width:100%" %>
  </div>
  <% if !current_user.nil? && current_user.admin? && !current_user?(@user) %>
    <div class="col s6 m3">
      <%= link_to raw("🤚&nbsp;&nbsp;Delete"), @user, method: :delete, data: { confirm: "You sure?" }, class: "waves-effect waves-light btn-large red mt-3", style: "width:100%" %>
    </div>
  <% end %>
  <% if current_user.admin?%>
    <div class="col s12 m3">
      <%= link_to raw("🤠&nbsp;&nbsp;Users"), users_path, class: "waves-effect waves-light btn-large blue-grey mt-3", style: "width:100%" %>
    </div>
  <% end  %>
</div>
<!--./ Nav Links -->