config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  get 'sessions/new'
  get 'users/new'
  get 'welcome/index'
  get 'appstore/likes'
  get 'appstore/dislikes'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    get :likes
    get :dislikes
  end

  resources :licenceplates do
    put :downvote
    put :upvote
    get :likes
    get :dislikes
  end
  resources :appstore do
    put :downvote
    put :upvote
    # get :likes
    # get :dislikes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/licenceplate.rb
# frozen_string_literal: true

class Licenceplate < ApplicationRecord
  acts_as_votable
  validates :plate, presence: true,
                    uniqueness: true,
                    length: { in: 6..7 },
                    format: { with: /\A[\d\a-z]{3} ?[\d\a-z]{3,4}\Z/i,
                              message: "entered is not a valid licence plate" }
end

app/controllers/licenceplates_controller.rb
# frozen_string_literal: true

class LicenceplatesController < ApplicationController
  before_action :logged_in_user, only: [:new]
  before_action :admin_user,     only: %i[update likes dislikes edit destroy]
  helper_method :sort_column, :sort_direction

  def index
    # @licenceplates = Licenceplate.all
    @licenceplates = Licenceplate.order(sort_column + " " + sort_direction)
  end

  def show
    @licenceplate = Licenceplate.find(params[:id])
  end

  def new
    @licenceplate = Licenceplate.new
  end

  def edit
    @licenceplate = Licenceplate.find(params[:id])
  end

  def update
    @licenceplate = Licenceplate.find(params[:id])

    if @licenceplate.update(licenceplate_params)
      redirect_to licenceplate_path
    else
      render 'edit'
    end
  end

  def create
    @licenceplate = Licenceplate.new(licenceplate_params)
    # Insert a space in the middle if the plate is length == 6
    if @licenceplate.plate.length == 6
      @licenceplate.plate.insert(3, " ")
    end
    if @licenceplate.save
      @licenceplate.plate.upcase!
      redirect_to @licenceplate
    elsif !@licenceplate.save && Licenceplate.exists?(plate: @licenceplate.plate)
      @existingplate = Licenceplate.find_by(plate: @licenceplate.plate)
      redirect_to licenceplate_url(@existingplate)
    elsif !@licenceplate.save
      render 'new'
    else
      render 'new'
    end
  end

  def destroy
    Licenceplate.find(params[:id]).destroy
    flash[:success] = "Licenceplate deleted"
    redirect_to licenceplates_path
  end

  def upvote
    @licenceplate = Licenceplate.find(params[:licenceplate_id])
    if !current_user.nil? && current_user.admin
      # @licenceplate.vote_by voter: current_user, :duplicate => true
      @licenceplate.upvote_from current_user
      redirect_to @licenceplate
    elsif !current_user.nil?
      @licenceplate.upvote_from current_user
      redirect_to @licenceplate
    else
      redirect_to login_url
    end
  end

  def downvote
    @licenceplate = Licenceplate.find(params[:licenceplate_id])
    if !current_user.nil? && current_user.admin
      # @licenceplate.vote_by voter: current_user, :duplicate => true
      @licenceplate.downvote_from current_user
      redirect_to @licenceplate
    elsif !current_user.nil?
      @licenceplate.downvote_from current_user
      redirect_to @licenceplate
    else
      redirect_to login_url
    end
  end

  def likes
    if !current_user.nil? && current_user.admin?
      @licenceplate = Licenceplate.find(params[:licenceplate_id])
      @likes = Licenceplate.find(params[:licenceplate_id]).get_likes
    else
      redirect_to licenceplates_path
    end
  end

  def dislikes
    if !current_user.nil? && current_user.admin?
      @licenceplate = Licenceplate.find(params[:licenceplate_id])
      @dislikes = Licenceplate.find(params[:licenceplate_id]).get_dislikes
    else
      redirect_to licenceplates_path
    end
  end

  def sort_column
    Licenceplate.column_names.include?(params[:sort]) ? params[:sort] : "plate"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  private

  def licenceplate_params
    params.require(:licenceplate).permit(:plate, :province)
  end

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = "Please log in."
    redirect_to login_url
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/licenceplates_helper.rb
# frozen_string_literal: true

module LicenceplatesHelper
end

app/views/licenceplates/_form.html.erb
<%= form_with model: @licenceplate, local: true do |form| %>
<% if @licenceplate.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@licenceplate.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <% @licenceplate.errors.full_messages.each do |msg| %>
      <p style="color:red;"><%= msg %></p>
    <% end %>
  </div>
  <% end %>
  <p>
    <label for="licenceplate_plate" class="active">Plate</label>
    <input type="text" value="<%= @licenceplate.plate.upcase %>" name="licenceplate[plate]">
  </p>

  <p>
    <label>Province</label>
    <select name="licenceplate[province]" class="browser-default">
      <option value="Quebec">Quebec</option>
      <option value="Ontario" disabled>Ontario</option>
      <option value="Manitoba" disabled>Manitoba</option>
      <option value="Saskatchewan" disabled>Saskatchewan</option>
      <option value="British Columbia" disabled>British Columbia</option>
      <option value="Nova Scotia" disabled>Nova Scotia</option>
      <option value="Prince Edward Island" disabled>Prince Edward Island</option>
      <option value="New Brunswick" disabled>New Brunswick</option>
      <option value="Newfoundland" disabled>Newfoundland</option>
    </select>
  </p>
  <%= form.submit "👌 Save changes", class: "waves-effect waves-light btn-large green mt-3" %>
  <span>&nbsp;&nbsp;</span>
  <%= link_to '👈 Back', licenceplate_path, class: "waves-effect waves-light btn-large blue mt-3" %>
  <% if !current_user.nil? && current_user.admin? %>
    <span>&nbsp;&nbsp;</span>
    <%= link_to "🤚 Delete", @licenceplate, method: :delete,
                                  data: { confirm: "You sure?" },
                                  class: "waves-effect waves-light btn-large red mt-3" %>
  <% end  %>
<% end %>

app/views/licenceplates/dislikes.html.erb
<% content_for :title, @licenceplate.plate.upcase %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<!-- Row -->
<div class="row mb-0">
  <div class="col m8 offset-m2 s12">
    <h4 class="hide-on-small-only">👎 Thumbs Down <%= @dislikes.size %></h4>
    <h4 class="center-align hide-on-med-and-up">👎 Thumbs Down <%= @dislikes.size %></h4>
  </div>
  <!-- Table -->
  <table class="striped centered col m8 offset-m2 s12">
    <!-- Table Headers -->
    <thead>
      <tr>
        <th><h5>🚘</h5></th>
        <th><h5>📆</h5></th>
      </tr>
    </thead>
    <!-- ./Table Headers -->
    <!-- Table Body -->
    <tbody>
    <% @dislikes.each do |dislike| %>
      <% if !dislike[:voter_id].nil? %>
        <tr>
          <td><%= link_to User.find(dislike[:voter_id]).name, user_path(dislike[:voter_id]) %></td>
          <td><%= dislike[:created_at].strftime("%Y-%m-%d") %></td>
        </tr>
      <% end %>
    <%end %>
    </tbody>
    <!-- ./Table Body -->
  </table>
  <!-- ./Table -->
</div>
<!-- ./Row -->

<!-- Nav Links -->
<div class="row center-align">
  <div class="col m6 offset-m3 s10 offset-s1">
    <%= link_to raw("👈&nbsp;Back"), licenceplate_path(@licenceplate), class: "waves-effect waves-light btn-large green mt-3", style: "width:100%" %>
  </div>
</div>

app/views/licenceplates/edit.html.erb
  <h1>Edit Licence Plate</h1>
  <%= render 'form' %>

app/views/licenceplates/index.html.erb
<% content_for :title, "All Rankings" %>

  <h2 class="center-align hide-on-small-only"><a href="https://instantcena.ca">All Rankings</a></h2>

  <!-- Row -->
  <div class="row center-align mb-0">
    <!-- Table -->
    <table class="striped centered">
      <!-- Table Headers -->
      <thead>
        <tr>
          <th><%= sortable "plate", raw("<h4>🚘</h4>") %></th>
          <th><h4>🇨🇦</h4></th>
          <th><h4>👍</h4></th>
          <th><h4>👎</h4></th>
          <% if !current_user.nil? && current_user.admin?%>
            <th><h4>🛑</h4></th>
          <% end %>
        </tr>
      </thead>
      <!-- ./Table Headers -->

      <!-- Table Body -->
      <tbody>
      <% @licenceplates.each do |licenceplate| %>
        <tr>
          <td><%= link_to licenceplate.plate.upcase, licenceplate_path(licenceplate) %></td>
          <td><%= licenceplate.province.capitalize %></td>
          <td><%= licenceplate.get_likes.size %></td>
          <td><%= licenceplate.get_downvotes.size %></td>
          <% if !current_user.nil? && current_user.admin?%>
            <td><%= link_to "Delete 🤚", licenceplate, method: :delete,
                                                            data: { confirm: "You sure?" }%>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
      <!-- ./Table Body -->
    </table>
    <!-- ./Table -->
  </div>
  <!-- ./Row -->

  <!-- Row -->
  <div class="row">
    <div class="col s10 offset-s1 m4 offset-m4">
      <%= link_to (raw("🚘&nbsp;&nbsp;Rate Someone")), new_licenceplate_path, class: "waves-effect waves-light btn-large green mt-3 px-3", style: "width:100%;", :method => :get %>
    </div>
    <div class="col s6 m3">
      <!-- <%= link_to "🏡 Home", welcome_index_path, class: "waves-effect waves-light btn-large blue mt-3", style: "width:100%;", :method => :get %> -->
    </div>
  </div>
  <!-- ./Row -->
  <!-- ./Row -->

app/views/licenceplates/likes.html.erb
<% content_for :title, @licenceplate.plate.upcase %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<!-- Row -->
<div class="row mb-0">
  <div class="col m8 offset-m2 s12">
    <h4 class="hide-on-small-only">👍 Thumbs Up <%= @likes.size %></h4>
    <h4 class="center-align hide-on-med-and-up">👍 Thumbs Up <%= @likes.size %></h4>
  </div>
  <!-- Table -->
  <table class="striped centered col m8 offset-m2 s12">
    <!-- Table Headers -->
    <thead>
      <tr>
        <th><h5>🚘</h5></th>
        <th><h5>📆</h5></th>
      </tr>
    </thead>
    <!-- ./Table Headers -->
    <!-- Table Body -->
    <tbody>
      <% @likes.each do |like| %>
        <% if !like[:voter_id].nil? %>
          <tr>
            <td><%= link_to User.find(like[:voter_id]).name, user_path(like[:voter_id]) %></td>
            <td><%= like[:created_at].strftime("%Y-%m-%d") %></td>
          </tr>
        <% end %>
      <%end %>
    </tbody>
    <!-- ./Table Body -->
  </table>
  <!-- ./Table -->
</div>
<!-- ./Row -->

<!-- Nav Links -->
<div class="row center-align">
  <div class="col m6 offset-m3 s10 offset-s1">
    <%= link_to raw("👈&nbsp;Back"), licenceplate_path(@licenceplate), class: "waves-effect waves-light btn-large green mt-3", style: "width:100%" %>
  </div>
</div>

app/views/licenceplates/new.html.erb
  <% content_for :title, "New Ranking" %>
  <!-- Form -->
  <%= form_with model: @licenceplate, local: true do |form| %>
    <!-- Licence Plate -->
    <div class="row my-4">
      <div class="col s12 m8 offset-m2">
        <div class="center-align z-depth-2"  id="licence_border">

          <div id="drill-hole">&nbsp;&nbsp;</div><!--  the drill holes -->
          <!-- Province Select -->
          <select id="plate-rovince" name="licenceplate[province]" class="browser-default">
            <option value="Quebec" selected="selected">Quebec</option>
            <option value="Ontario" disabled>Ontario</option>
            <option value="Manitoba" disabled>Manitoba</option>
            <option value="Saskatchewan" disabled>Saskatchewan</option>
            <option value="British Columbia" disabled>British Columbia</option>
            <option value="Nova Scotia" disabled>Nova Scotia</option>
            <option value="Prince Edward Island" disabled>Prince Edward Island</option>
            <option value="New Brunswick" disabled>New Brunswick</option>
            <option value="Newfoundland" disabled>Newfoundland</option>
          </select>
          <!-- ./ Province Select -->
          <div id="drill-hole">&nbsp;&nbsp;</div><!--  the drill holes -->

          <!-- Licence Plate Input -->
          <h1>
            <input onkeyup="formatInput();" id="plate-input" class="center-align" type="text" name="licenceplate[plate]" placeholder="B01 AAA" maxlength="7"/>
          </h1>
          <!-- ./Licence Plate Input -->

          <div id="drill-hole">&nbsp;&nbsp;</div><!--  the drill holes -->
          <h5 id="plate-province-text">Je me souviens</h5>
          <div id="drill-hole">&nbsp;&nbsp;</div><!--  the drill holes -->

        </div>
      </div>
    </div>
    <!-- ./ Licence Plate -->

    <!-- Submit & Buttons -->
    <div class="row">
      <div class="col s5 offset-s1 m3 offset-m3">
        <%= form.submit raw("👍&nbsp;&nbsp;Submit"), class: "waves-effect waves-light btn-large green mt-0", style: "width:100%;", id: "new-plate-submit" %>
      </div>
      <div class="col s5 m3">
        <%= link_to raw("🏁&nbsp;&nbsp;Ranks"), licenceplates_path, class: "waves-effect waves-light btn-large blue mt-0", style: "width:100%;", :method => :get %>
      </div>
    </div>
    <!-- Submit & Buttons -->

    <!-- Error Messages -->
    <% if @licenceplate.errors.any? %>
      <div class="row center-align">
        <div id="error_explanation">
          <h6>
            <%= pluralize(@licenceplate.errors.count, "error") %> prohibited rating the licence plate.
          </h6>
          <% @licenceplate.errors.full_messages.each do |msg| %>
            <p style="color:red;" class="center-align">🤦‍♂️ <%= raw msg %></p>
          <% end %>
        </div>
      </div>
    <% end %>
    <!-- ./ Error Messages -->
  <% end %>
  <!-- End Form -->

app/views/licenceplates/show.html.erb
<% content_for :title, @licenceplate.plate.upcase %>
<!-- Licence Plate -->
<div class="row section mb-3">
  <div class="col s12 m8 offset-m2">
    <div class="center-align z-depth-2"  id="licence_border">

      <div id="drill-hole">&nbsp;&nbsp;</div><!--  the drill holes -->
      <h5 id="plate-province"><%= @licenceplate.province %></h5>
      <div id="drill-hole">&nbsp;&nbsp;</div><!--  the drill holes -->

      <h1><%= @licenceplate.plate.upcase %></h1>

      <div id="drill-hole">&nbsp;&nbsp;</div><!--  the drill holes -->
      <h5 id="plate-province-text">Je me souviens</h5>
      <div id="drill-hole">&nbsp;&nbsp;</div><!--  the drill holes -->
    </div>
  </div>
</div>
<!-- ./ Licence Plate -->

<!-- Votes -->
<div class="row center-align">
  <div class="col s3 m4 right-align">
    <h5 id="votes" class="green-text"><%= @licenceplate.get_upvotes.size%></h5>
  </div>
  <div class="col s3 m2">
    <a class="btn-floating btn-large waves-effect waves-light green" data-method="put" href="/licenceplates/<%= @licenceplate.id %>/upvote">👍</a>
  </div>
  <div class="col s3 m2">
    <a class="btn-floating btn-large waves-effect waves-light red" data-method="put" href="/licenceplates/<%= @licenceplate.id %>/downvote">👎</a>
  </div>
  <div class="col s3 m4 left-align">
    <h5 id="votes" class="red-text"><%= @licenceplate.get_downvotes.size%></h5>
  </div>
</div>
<!-- ./ Votes -->

<!-- Nav Links -->
<div class="row center-align mb-3">
  <div class="col s5 offset-s1 m3 offset-m3">
    <%= link_to raw("👈&nbsp;&nbsp;Back"), licenceplates_path, class: "waves-effect waves-light btn-large green mt-3", style: "width:100%;", :method => :get %>
  </div>
  <div class="col s5 m3">
    <button onclick="showchat();" class="waves-effect waves-light btn-large blue mt-3"  style="width:100%;",>💬&nbsp;Chat</button>
  </div>
  <% if !current_user.nil? && current_user.admin?%>
    <div class="col s5 offset-s1 m3 offset-m3">
      <%= link_to "✏️  Edit",  edit_licenceplate_path, class: "waves-effect waves-light btn-large green mt-3", style: "width:100%;", :method => :get %>
    </div>
    <div class="col s5 m3 ">
      <%= link_to "🤚  Delete", @licenceplate, method: :delete, data: { confirm: "You sure?" }, class: "waves-effect waves-light btn-large red mt-3", style: "width:100%;" %>
    </div>
  <% end  %>
</div>
<% if !current_user.nil? && current_user.admin? %>
  <div class="row center-align mb-3">
      <div class="col s5 offset-s1 m3 offset-m3">
        <a class="btn-large waves-effect waves-light green" style="width:100%" data-method="get" href="/licenceplates/<%= @licenceplate.id %>/likes">👍</a>
      </div>
      <div class="col s5 m3 ">
        <a class="btn-large waves-effect waves-light red" style="width:100%" data-method="get" href="/licenceplates/<%= @licenceplate.id %>/dislikes">👎</a>
      </div>
  </div>
<% end %>
<!-- ./ Nav Links -->

<!-- Disqus -->
<div class="row mb-3">
  <div class="col s12 m8 offset-m2">
    <div id="disqus_thread"></div>
  </div>
</div>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<!-- Some Diquss Business -->
<script id="dsq-count-scr" src="//driverrank-ca.disqus.com/count.js" async></script>
<!-- ./ Disqus -->