config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  get 'sessions/new'
  get 'users/new'
  get 'welcome/index'
  get 'appstore/likes'
  get 'appstore/dislikes'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    get :likes
    get :dislikes
  end

  resources :licenceplates do
    put :downvote
    put :upvote
    get :likes
    get :dislikes
  end
  resources :appstore do
    put :downvote
    put :upvote
    # get :likes
    # get :dislikes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <!-- Favicon -->
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <link rel="apple-touch-icon" href="<%= asset_path('apple-touch-icon.png')%>">
    <link rel="apple-touch-startup-image" href="<%= asset_path('launch.png')%>">
    <!-- Meta Tags -->
    <meta name="apple-mobile-web-app-title" content="Driver Rank">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="keywords" content="driver rank,driver,rank,driving,social,rate,rating,ranking,bad driver,good driver">
    <meta name="author" content="Kevin Camellini">
    <!-- Import Font Awesome -->
    <script src="https://use.fontawesome.com/8f2ae3cde2.js"></script>
    <!-- Import Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Bootstrap Margin/Padding CSS -->
    <%= stylesheet_link_tag "bootstrap-padding.css" %>
    <!-- Import Materialize.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <!-- Import jQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <!-- Import Materialize.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper blue">
        <%= link_to (raw("🚘 Driver <strong>Rank</strong><small style=\"font-size:15px;color:red;\">&nbsp;beta</small>")), root_path, class: "pl-4 brand-logo left" %>
        <ul class="right">
        <% if logged_in? %>
          <li class="hide-on-small-only"><%= link_to current_user.name, current_user %></li>
          <li class="hide-on-med-and-up"><%= link_to "👤", current_user %></li>
          <!-- <li><%# link_to "✏️", edit_user_path(current_user), style: "font-size: 1.3em;" %></li> -->
          <li><%= link_to (raw("<span>🔒</span>")), logout_path, method: :delete, style: "font-size: 1.3em;", id: "logout-emoji" %></li>
        <% else %>
          <!-- <li><%# link_to (raw("<span>Register ✏️</span>")), users_new_path, class: "pr-0"%></li> -->
          <li><%= link_to (raw("<span>Login 🔓</span>")), login_path, id: "login-emoji" %></li>
        <% end %>
        </ul>
      </div>
    </nav>

    <main class=" grey lighten-4">
      <!-- Container -->
      <div class="container">
        <%= yield %>
      </div>
      <!-- /.Container -->
    </main>

    <!-- Zoom Zoom Car -->
    <% if current_page?('/licenceplates/new')%>
      <div id="canvas">
        <p id="zoomzoom">🚗</p>
      </div>
    <% end %>
    <!-- ./ Zoom Zoom Car -->

    <!-- Footer -->
    <footer class="blue darken-2">
        <div class="container">
          <div class="row py-5 my-0 p-xs-3">
            <div class="col s7 px-0 pt-xs-3" id="signature">
              <a href="https://kcamel.com" class="grey-text text-lighten-3">
                <i class="fa fa-chevron-left"></i>
                <i class="fa fa-chevron-right"></i>
                with
                <i class="fa fa-heart"></i>
                by
                <span class="footer_name">Kevin&nbsp;Camellini</span>
              </a>
              <br/>
              <div class="grey-text text-lighten-2 mt-2">&copy;&nbsp;DriverRank.ca <span id="yearfooter"></span></div>
            </div>
            <div class="col s5 px-0 right-align grey-text text-lighten-2">
              <%= link_to (raw("iPhone&nbsp;<i class=\"fa fa-apple\"></i>")), appstore_index_path, id: "footer-button", class: "btn blue grey-text text-lighten-3"%>
              <%= link_to (raw("Android&nbsp;<i class=\"fa fa-android\"></i>")), appstore_index_path, id: "footer-button", class: "btn blue grey-text text-lighten-3"%>
            </div>
          </div>
        </div>
        <!-- /.container -->
    </footer>
    <!-- /.Footer     -->
  </body>
</html>